In [ ]:
#웹페이지 부분

import requests

URL = 'http://www.naver.com'
response = requests.get(URL)
print(response.status_code)
print(response.text)

In [ ]:
URL = 'http://www.naver.com/search.naevr'
params = {'query' : 'aa'}
response = requests.get(URL, params=params)
print(response.status_code)
print(response.text)

In [ ]:
f= open('web/test.html', 'w', encoding='UTF-8')
URL = 'http://search.naver.com/search.naver'
params = {'query' : 'lol'}
response = requests.get(URL, params=params)
print(response.status_code)
html_sor = response.text
f.write(html_sor)
f.close

In [ ]:
f= open('web/webtoon.html', 'w', encoding='UTF-8')
URL = 'https://comic.naver.com/webtoon/detail'
params = {'titleId' : 783054, 'no' : 48}
response = requests.get(URL, params=params)
html_sor = response.text
f.write(html_sor)
f.close

In [ ]:
import datetime as dt

today = dt.datetime.today().weekday()
days = ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일']
webtoon_lst = {days[0]:"183559", days[1]:"784248",days[2]:"738694",
                days[3]:"747271",days[4]:"773797",days[5]:"773796",days[6]:"774844"}

f= open('web/webtoon12.html', 'w', encoding='UTF-8')
URL = 'https://comic.naver.com/webtoon/detail.nhn'
params = {'titleId' : webtoon_lst[days[today]]}
response = requests.get(URL,params=params)
html_sor = response.text
f.write(html_sor)
f.close

In [ ]:
f= open('web/webtoon12.html', 'w', encoding='UTF-8')
URL = 'https://freemeteo.kr/weather/chonan/hourly-forecast/today/'
params = {'lanuage' : 'korean', 'gid' : '1845759'}
response = requests.get(URL,params=params)
html_sor = response.text
f.write(html_sor)
f.close

In [ ]:
f= open('web/webtoon123.html', 'w', encoding='UTF-8')
URL = 'https://news.naver.com/'
response = requests.get(URL)
html_sor = response.text
f.write(html_sor)
f.close

In [ ]:
# f= open('web/test.html', 'w', encoding='UTF-8')
URL = 'https://www.naver.com/'
response_ = requests.get(URL)
html_data = response_.text
# f.write(html_data)

a = open('web/test.html', 'r', encoding='UTF-8')
data = a.read()
# print(data.find('<div class="title_area">'))
# print(data[58676:58743])
temp = data[58676:58743]
# print(temp.find("오"))
print(temp[49: 58])


k = ['','"ENTER">', '"SPORTS">', '"CARGAME">']
for i in range(len(k)):
    if i > 0:
        s = data.split('<a href="#" role="tab" class="_NM_THEME_CATE tab id_')[i]
        s = data.split(k[i])[1].split('</a>')[0]
        print(s)


In [ ]:
#뉴스 랭킹 표시
f= open('web/test1.html', 'w', encoding='UTF-8')
URL = 'https://media.naver.com/press/055/ranking'
params = {'type' : 'popular'}
response_ = requests.get(URL, params=params)
html_data = response_.text
f.write(html_data)

In [ ]:
a = open('web/test1.html', 'r', encoding='UTF-8')
data = a.read()
print(data.find('<strong class="list_title">'))
print(data[49259:49286])
temp = data[49259:49286]


for i in range(20):

    
    s = data.split('<strong class="list_title">')[i]
    s = data.split(s)[1].split('</strong>')[0]
    
    print(i+1, s[27:])

In [ ]:
#웹 크롤링 미완성
import selenium
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
import time

driver = webdriver.Chrome()
driver.get('https://www.dhlottery.co.kr/gameResult.do?method=statByNumber')

element = Select(driver.find_element_by_id('sltBonus'))
element.select_by_value('0')
time.sleep(2)
element = driver.find_element_by_class_name('btn_common.mid.blu')
element.click()

f= open('web/lotto.html', 'w', encoding='UTF-8')


In [7]:
from bs4 import BeautifulSoup

import requests
import numpy as np
import time as t

req = requests.get('https://www.dhlottery.co.kr/gameResult.do?method=statByNumber')
html = req.text

soup = BeautifulSoup(html, 'html.parser')
result = soup.find_all('tbody')
result1 = soup.find_all('td')[0] #4 >> +3 1:4 2:7 3:10 ... 136
per = []
for i in range(4, 137, 3):
    per.append(int(soup.find_all('td')[i].get_text()))
z = []
for i in range(len(per)):
    z.append(per[i] / sum(per))


print(sum(z))

a = np.arange(1,46)
for i in range(5):
    b = np.random.choice(a, 6, replace= False, p = z)
    print(np.sort(b))
#결과물 웹사이트에 올리기

1.0
[ 5 11 13 14 36 41]
[ 7 16 23 24 33 40]
[17 23 24 25 33 39]
[ 1 22 30 31 43 45]
[ 6 11 29 34 35 37]


In [15]:
f= open('web/soup_.html', 'r', encoding='UTF-8')
soup = BeautifulSoup(f, 'html.parser')
con = soup.find('body')

p_ = con.find('p', class_ = "b")
print(p_)
print(p_.find_next_siblings())

<p align="center" class="b">text2</p>
[<p align="center" class="c">text3</p>, <div><img height="200" src="/source" width="300"/></div>]
